# Generated by Django 5.0.6 on 2024-07-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='people',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
