# Generated by Django 5.0.6 on 2024-08-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_inquiry_people_alter_inquiry_travel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_modal', models.BooleanField(default=False)),
            ],
        ),
    ]
